### PR TITLE
Re-doing "Remove PNG imports"

### PR DESCRIPTION
**Pull request by olemartinorg**
## Description
In #215, png imports were removed in order to make builds easier for projects importing the design system (by not requiring to support png files in their build systems, unless explicitly needed when using the map component). This change was a good step forward, but came at a bad time - breaking [app-frontend-react](https://github.com/Altinn/app-frontend-react/) at a very bad time. Now is the time to clean up and pay this debt, fixing app-frontend-react so the map component works properly - even with this change in the design system.

## Related Issue(s)
- #215 
- #216

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

### CODE REVIEW

**Comment by olemartinorg** [comment]
I've been looking into this a bit more today, and this doesn't look like a silver bullet quite yet. As far as I can tell, `leaflet` and `react-leaflet` are local dependencies in `altinn-design-system/package.json`, and when it builds (without PNG imports and the PNG support in rollup), the resulting package does not include the default map marker images (such as `images/marker-icon.png`).

@TomasEng You've [tested the map component in Studio](https://github.com/Altinn/altinn-design-system/pull/216#issuecomment-1332043614) (via the design system), right? Could we find some time to collaborate and figure out how that worked, and how we could get it working in `app-frontend-react` as well? :pray:

**Comment by olemartinorg** [comment]
@TomasEng Never mind! I think I found a working solution (it works for `app-frontend-react`, at least). No you'll have to inject the marker icon yourself (but you can load it from `leaflet` since that's shipped into your `node_modules` alongside the design system).

**Review by TomasEng — APPROVED** [review]
Excellent, @olemartinorg! I think this is better, since it only requires the consumer to do something if they use the component. I was also considering hard coding a data URL, but that's not ideal since the icon might change in future versions of Leaflet. Let's go for this!

**Comment by olemartinorg** [comment]
@DanRJ Happy new year! :fireworks: Hoping `v0.25.13` is a smoother ride for you now, without having to implement image file loading in your build pipeline when using the design system. :blush:

**Pull request merged**
